

CREATE TABLE CADENA_DE_HOTELES(
	Id			NUMBER		NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL);

CREATE TABLE PLANES_DE_CONSUMO(
	Id			NUMBER		NOT NULL,
	IdHotel			NUMBER		NOT NULL,
	Descripcion		VARCHAR(1000)	NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL,
	FechaInicio		DATE,		
	FechaFin		DATE		);

CREATE TABLE RESERVAS_SERVICIOS(
	Id			NUMBER		NOT NULL,
	Descripcion		VARCHAR(100)	NOT NULL,
	FechaInicio		DATE		NOT NULL,
	FechaFin		DATE		NOT NULL,
	IdServicio		NUMBER		NOT NULL,
	TipoIdentificacion	VARCHAR(30)	NOT NULL,
	IdTipoPersona		NUMBER		NOT NULL);

CREATE TABLE 	 RESERVAS_DE_ALOJAMIENTO(
	Id			NUMBER		NOT NULL,
	IdHabitacion		NUMBER		NOT NULL,
	IdHotel			NUMBER		NOT NULL,
	FechaLlegadaTeorica	DATE		NOT NULL,
	FechaLlegadaReal	DATE		,
	FechaSalidaTeorica	DATE		NOT NULL,
	FechaSalidaReal		DATE		,
	PlanDeConsumo		NUMBER			);

CREATE TABLE HOTELES(
	Id			NUMBER		NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL,
	Estrellas		INTEGER		NOT NULL,
	IdCadenaHoteles		NUMBER		NOT NULL);

CREATE TABLE PERSONAS(
	Id			NUMBER		NOT NULL,
	TipoIdentificacion	VARCHAR(30)	NOT NULL,
	IdHotel			NUMBER,
	IdTipoPersona		NUMBER		NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL,
	Correo			VARCHAR(30)	NOT NULL);

CREATE TABLE HABITACIONES(
	Numero			NUMBER		NOT NULL,
	IdHotel			NUMBER		NOT NULL,
	TipoHabitacion		NUMBER		NOT NULL);

CREATE TABLE SERVICIOS_ADICIONALES(
	Id			NUMBER		NOT NULL,
	IdHotel			NUMBER		NOT NULL,
	Categoria		VARCHAR(30)	NOT NULL,
	EstaIncluido		INTEGER		NOT NULL,
	HorarioInicio		VARCHAR(30)	NOT NULL,
	HorarioFin		VARCHAR(30)     NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL,
	Valor			NUMBER		NOT NULL,
	Descripcion		VARCHAR(100)	NOT NULL);

CREATE TABLE TIPOS_DE_PERSONAS(
	Id			NUMBER		NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL);

CREATE TABLE TIPOS_DE_HABITACION(
	Id			NUMBER		NOT NULL,
	Capacidad		INTEGER		NOT NULL,
	CostoAlojamientoNoche	NUMBER		NOT NULL,
	Dotacion		VARCHAR(100)	NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL);

CREATE TABLE GASTOS(
	Id			NUMBER		NOT NULL,
	IdUsuario		NUMBER		NOT NULL,
	IdTipoIdentificacion	VARCHAR(30)	NOT NULL,
	IdServicio		NUMBER		NOT NULL,
	Fecha			DATE		NOT NULL,
	Pagado			INTEGER		NOT NULL,
	Precio			NUMBER		NOT NULL);

CREATE TABLE PRODUCTOS(
	Id			NUMBER		NOT NULL,
	Nombre			VARCHAR(30)	NOT NULL,
	IdServicio		NUMBER		NOT NULL);

CREATE TABLE RESERVAS_DE_CLIENTES(
	IdReserva		NUMBER		NOT NULL,
	IdUsuario		NUMBER		NOT NULL,
	TipoIdUsuario		NUMBER		NOT NULL);

