--------------------------------------------------------
-- Archivo creado  - miércoles-abril-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESERVAS_SERVICIOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE, 
	"IDSERVICIO" NUMBER, 
	"IDTIPOPERSONA" NUMBER, 
	"TIPOIDENTIFICACION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CADENA_DE_HOTELES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."CADENA_DE_HOTELES" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table GASTOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."GASTOS" 
   (	"ID" NUMBER, 
	"IDSERVICIO" NUMBER, 
	"FECHA" DATE, 
	"PAGADO" NUMBER(*,0), 
	"PRECIO" FLOAT(126), 
	"IDRESERVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table HABITACIONES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."HABITACIONES" 
   (	"NUMERO" NUMBER, 
	"IDHOTEL" NUMBER, 
	"TIPOHABITACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table HOTELES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."HOTELES" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"ESTRELLAS" NUMBER(*,0), 
	"IDCADENAHOTELES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."PERSONAS" 
   (	"ID" NUMBER, 
	"TIPOIDENTIFICACION" VARCHAR2(30 BYTE), 
	"IDHOTEL" NUMBER, 
	"IDTIPOPERSONA" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"CORREO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."PRODUCTOS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"IDSERVICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PLANES_DE_CONSUMO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" 
   (	"ID" NUMBER, 
	"IDHOTEL" NUMBER, 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table RESERVAS_DE_ALOJAMIENTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" 
   (	"ID" NUMBER, 
	"IDHABITACION" NUMBER, 
	"IDHOTEL" NUMBER, 
	"FECHALLEGADATEORICA" DATE, 
	"FECHALLEGADAREAL" DATE, 
	"FECHASALIDATEORICA" DATE, 
	"FECHASALIDAREAL" DATE, 
	"PLANDECONSUMO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table RESERVAS_DE_CLIENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" 
   (	"IDRESERVA" NUMBER, 
	"IDUSUARIO" NUMBER, 
	"TIPOIDUSUARIO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table SERVICIOS_ADICIONALES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" 
   (	"ID" NUMBER, 
	"IDHOTEL" NUMBER, 
	"CATEGORIA" VARCHAR2(30 BYTE), 
	"ESTAINCLUIDO" NUMBER(*,0), 
	"HORARIOINICIO" VARCHAR2(30 BYTE), 
	"HORARIOFIN" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"VALOR" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table TIPOS_DE_HABITACION
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" 
   (	"ID" NUMBER, 
	"CAPACIDAD" NUMBER(*,0), 
	"COSTOALOJAMIENTONOCHE" FLOAT(126), 
	"DOTACION" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table TIPOS_DE_PERSONAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B181910"."TIPOS_DE_PERSONAS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDRESERVASSERVICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDRESERVASSERVICIOS_PK" ON "ISIS2304B181910"."RESERVAS_SERVICIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDHOTELES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDHOTELES_PK" ON "ISIS2304B181910"."CADENA_DE_HOTELES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDGATOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDGATOS_PK" ON "ISIS2304B181910"."GASTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index NUMEROHABITACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."NUMEROHABITACIONES_PK" ON "ISIS2304B181910"."HABITACIONES" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDHOTELESHOTELES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDHOTELESHOTELES_PK" ON "ISIS2304B181910"."HOTELES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDPERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDPERSONAS_PK" ON "ISIS2304B181910"."PERSONAS" ("ID", "TIPOIDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDDELPRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDDELPRODUCTO_PK" ON "ISIS2304B181910"."PRODUCTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDPLANES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDPLANES_PK" ON "ISIS2304B181910"."PLANES_DE_CONSUMO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDRESERVASALOJAMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDRESERVASALOJAMIENTO_PK" ON "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index RESERVAS_DE_CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."RESERVAS_DE_CLIENTES_PK" ON "ISIS2304B181910"."RESERVAS_DE_CLIENTES" ("IDRESERVA", "IDUSUARIO", "TIPOIDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index NUMEROSERVICIOSADICIONALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."NUMEROSERVICIOSADICIONALES_PK" ON "ISIS2304B181910"."SERVICIOS_ADICIONALES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDTIPOSHABITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDTIPOSHABITACION_PK" ON "ISIS2304B181910"."TIPOS_DE_HABITACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index IDTIPOSPERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B181910"."IDTIPOSPERSONAS_PK" ON "ISIS2304B181910"."TIPOS_DE_PERSONAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table RESERVAS_SERVICIOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" MODIFY ("TIPOIDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" MODIFY ("IDTIPOPERSONA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" MODIFY ("FECHAFIN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" MODIFY ("FECHAINICIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" ADD CONSTRAINT "IDRESERVASSERVICIOS_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CADENA_DE_HOTELES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."CADENA_DE_HOTELES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."CADENA_DE_HOTELES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."CADENA_DE_HOTELES" ADD CONSTRAINT "IDHOTELES_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GASTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."GASTOS" MODIFY ("IDRESERVA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."GASTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."GASTOS" MODIFY ("PAGADO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."GASTOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."GASTOS" MODIFY ("IDSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."GASTOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."GASTOS" ADD CONSTRAINT "IDGATOS_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B181910"."GASTOS" ADD CONSTRAINT "GASTOS_CK" CHECK (Pagado = 0 AND Precio >= 0 OR Pagado = 1 AND Precio >= 0 OR  Pagado = 2 AND Precio >= 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table HABITACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."HABITACIONES" MODIFY ("TIPOHABITACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HABITACIONES" MODIFY ("IDHOTEL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HABITACIONES" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HABITACIONES" ADD CONSTRAINT "NUMEROHABITACIONES_PK" PRIMARY KEY ("NUMERO") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOTELES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."HOTELES" MODIFY ("IDCADENAHOTELES" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HOTELES" MODIFY ("ESTRELLAS" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HOTELES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HOTELES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."HOTELES" ADD CONSTRAINT "IDHOTELESHOTELES_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B181910"."HOTELES" ADD CONSTRAINT "ESTRELLASHOTELES_CK" CHECK (Estrellas>=0 AND Estrellas <=5) ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."PERSONAS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PERSONAS" MODIFY ("IDTIPOPERSONA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PERSONAS" MODIFY ("TIPOIDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PERSONAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PERSONAS" ADD CONSTRAINT "IDPERSONAS_PK" PRIMARY KEY ("ID", "TIPOIDENTIFICACION") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B181910"."PERSONAS" ADD CONSTRAINT "CORREOPERSONAS_CK" CHECK (Correo LIKE ('%@%')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."PRODUCTOS" MODIFY ("IDSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PRODUCTOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PRODUCTOS" ADD CONSTRAINT "IDDELPRODUCTO_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANES_DE_CONSUMO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" MODIFY ("IDHOTEL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" ADD CONSTRAINT "IDPLANES_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVAS_DE_ALOJAMIENTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" MODIFY ("FECHASALIDATEORICA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" MODIFY ("FECHALLEGADATEORICA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" MODIFY ("IDHOTEL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" MODIFY ("IDHABITACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ADD CONSTRAINT "IDRESERVASALOJAMIENTO_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ADD CONSTRAINT "FECHADESALIDAMAYOR_CK" CHECK (FechaLlegadaTeorica < FechaSalidaTeorica) ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVAS_DE_CLIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" MODIFY ("TIPOIDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" MODIFY ("IDRESERVA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" ADD CONSTRAINT "RESERVAS_DE_CLIENTES_PK" PRIMARY KEY ("IDRESERVA", "IDUSUARIO", "TIPOIDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICIOS_ADICIONALES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("HORARIOFIN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("HORARIOINICIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("ESTAINCLUIDO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("IDHOTEL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" ADD CONSTRAINT "NUMEROSERVICIOSADICIONALES_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" ADD CONSTRAINT "ESTAINCLUIDOSERVICIOSA_CK" CHECK (EstaIncluido = 0 OR EstaIncluido = 1) ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOS_DE_HABITACION
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" ADD CONSTRAINT "TIPOSDEHABITACION_CK" CHECK (Capacidad > 0 AND CostoAlojamientoNoche >0) ENABLE;
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" MODIFY ("DOTACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" MODIFY ("COSTOALOJAMIENTONOCHE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" MODIFY ("CAPACIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_HABITACION" ADD CONSTRAINT "IDTIPOSHABITACION_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOS_DE_PERSONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_PERSONAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B181910"."TIPOS_DE_PERSONAS" ADD CONSTRAINT "IDTIPOSPERSONAS_PK" PRIMARY KEY ("ID") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS_SERVICIOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."RESERVAS_SERVICIOS" ADD CONSTRAINT "IDUSUARIOSERVICIOSR_FK" FOREIGN KEY ("IDTIPOPERSONA", "TIPOIDENTIFICACION")
	  REFERENCES "ISIS2304B181910"."PERSONAS" ("ID", "TIPOIDENTIFICACION") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GASTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."GASTOS" ADD CONSTRAINT "GASTOS_FK1" FOREIGN KEY ("IDRESERVA")
	  REFERENCES "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ("ID") ENABLE;
  ALTER TABLE "ISIS2304B181910"."GASTOS" ADD CONSTRAINT "IDSERVICIOGATOS_FK" FOREIGN KEY ("IDSERVICIO")
	  REFERENCES "ISIS2304B181910"."SERVICIOS_ADICIONALES" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HABITACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."HABITACIONES" ADD CONSTRAINT "IDHOTELHABITACIONES_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304B181910"."HOTELES" ("ID") RELY ENABLE;
  ALTER TABLE "ISIS2304B181910"."HABITACIONES" ADD CONSTRAINT "TIPOHABITACIONHABITACIONES_FK" FOREIGN KEY ("TIPOHABITACION")
	  REFERENCES "ISIS2304B181910"."TIPOS_DE_HABITACION" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOTELES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."HOTELES" ADD CONSTRAINT "IDCADENAHOTELESHOTELES_FK" FOREIGN KEY ("IDCADENAHOTELES")
	  REFERENCES "ISIS2304B181910"."CADENA_DE_HOTELES" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."PERSONAS" ADD CONSTRAINT "IDHOTELPERSONAS_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304B181910"."HOTELES" ("ID") RELY ENABLE;
  ALTER TABLE "ISIS2304B181910"."PERSONAS" ADD CONSTRAINT "IDTIPOPERSONAPERSONAS_FK" FOREIGN KEY ("IDTIPOPERSONA")
	  REFERENCES "ISIS2304B181910"."TIPOS_DE_PERSONAS" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."PRODUCTOS" ADD CONSTRAINT "SERVICIODELPRODUCTO_FK" FOREIGN KEY ("IDSERVICIO")
	  REFERENCES "ISIS2304B181910"."SERVICIOS_ADICIONALES" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANES_DE_CONSUMO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."PLANES_DE_CONSUMO" ADD CONSTRAINT "IDHOTELPLANES_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304B181910"."HOTELES" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS_DE_ALOJAMIENTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ADD CONSTRAINT "IDHABITACIONRESERVASA_FK" FOREIGN KEY ("IDHABITACION")
	  REFERENCES "ISIS2304B181910"."HABITACIONES" ("NUMERO") RELY ENABLE;
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ADD CONSTRAINT "IDHOTELRESERVASA_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304B181910"."HOTELES" ("ID") RELY ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS_DE_CLIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" ADD CONSTRAINT "RESERVAS_DE_CLIENTES_FK1" FOREIGN KEY ("IDUSUARIO", "TIPOIDUSUARIO")
	  REFERENCES "ISIS2304B181910"."PERSONAS" ("ID", "TIPOIDENTIFICACION") ENABLE;
  ALTER TABLE "ISIS2304B181910"."RESERVAS_DE_CLIENTES" ADD CONSTRAINT "RESERVAS_DE_CLIENTES_FK2" FOREIGN KEY ("IDRESERVA")
	  REFERENCES "ISIS2304B181910"."RESERVAS_DE_ALOJAMIENTO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICIOS_ADICIONALES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B181910"."SERVICIOS_ADICIONALES" ADD CONSTRAINT "IDHOTELSERVICIOSA_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304B181910"."HOTELES" ("ID") RELY ENABLE;
